version: "3.9"

services:
  db:
    image: postgres:16
    container_name: chill-postgres
    restart: always
    environment:
      POSTGRES_USER: chilluser
      POSTGRES_PASSWORD: chill123
      POSTGRES_DB: chilldb
    ports:
      - "5432:5432"
    volumes:
      - chill_pgdata:/var/lib/postgresql/data

volumes:
  chill_pgdata:
